In [3]:
import numpy as np

In [11]:
mio_array=np.array([-21,45,30,0,-150,55,90,23])
mio_array

array([ -21,   45,   30,    0, -150,   55,   90,   23])

In [12]:
cinque_mio_array=0==(mio_array % 5)
cinque_mio_array

array([False,  True,  True,  True,  True,  True,  True, False])

In [13]:
mio_sub_array=mio_array[cinque_mio_array]
mio_sub_array

array([  45,   30,    0, -150,   55,   90])

In [14]:
mio_sub2_array=mio_sub_array[mio_sub_array>0]

In [15]:
mio_sub2_array

array([45, 30, 55, 90])

In [16]:
mio_sub_array

array([  45,   30,    0, -150,   55,   90])

In [18]:
mio_maggiore_zero=mio_array>0
mio_and_array=np.logical_and(cinque_mio_array,mio_maggiore_zero)
mio_and_array

array([False,  True,  True, False, False,  True,  True, False])

In [19]:
mio_array[mio_and_array]

array([45, 30, 55, 90])

In [20]:
mio_or_array=np.logical_or(cinque_mio_array,mio_maggiore_zero)
mio_or_array

array([False,  True,  True,  True,  True,  True,  True,  True])

In [21]:
mio_array[mio_or_array]

array([  45,   30,    0, -150,   55,   90,   23])

In [22]:
mio_not_array=np.logical_not(cinque_mio_array,mio_maggiore_zero)
mio_not_array

array([ True, False, False, False, False, False, False,  True])

In [24]:
mio_array[mio_not_array]

array([-21,  23])