In [3]:
import numpy as np

In [4]:
mia_lista=[1,2,3,4,5]

In [7]:
mio_array=np.array(mia_lista)

In [8]:
mio_array

array([1, 2, 3, 4, 5])

In [9]:
mio_array.dtype

dtype('int32')

In [10]:
mio_array.size

5

In [11]:
len(mio_array)

5

In [12]:
mio_array.nbytes

20

In [29]:
mia_lista_multi=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

In [ ]:
mio_array_multi=np.array(mia_lista_multi)

In [30]:
mio_array_multi

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
mio_array_multi.shape

(3, 5)

In [32]:
mio_array_multi.nbytes

60

In [33]:
mio_array_multi.size

15

In [36]:
mio_array_multi.dtype

dtype('int32')

In [38]:
mio_array_zero=np.zeros(5)

In [39]:
mio_array_zero

array([0., 0., 0., 0., 0.])

In [40]:
mio_array_zero_int=np.zeros(5,int)

In [41]:
mio_array_zero_int

array([0, 0, 0, 0, 0])

In [42]:
mio_array_one=np.ones(5)

In [43]:
mio_array_one

array([1., 1., 1., 1., 1.])

In [44]:
mio_array_one_int=np.ones(5,int)

In [45]:
mio_array_one_int

array([1, 1, 1, 1, 1])

In [48]:
mio_linspace=np.linspace(0,10,40)

In [49]:
mio_linspace

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [55]:
mio_eye = np.eye(8, dtype = float)

In [56]:
mio_eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
mio_eye_shift = np.eye(8,5,k=1, dtype = int)

In [62]:
mio_eye_shift

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])