In [1]:
import numpy as np

In [2]:
mia_lista=[1,2,3,4,5]

In [3]:
mio_array=np.array(mia_lista)

In [4]:
mio_array

array([1, 2, 3, 4, 5])

In [5]:
primo_elemento=mio_array[0]
primo_elemento

1

In [6]:
ultimo_elemento=mio_array[-1]
ultimo_elemento

5

In [8]:
alcuni_elementi=mio_array[1:4]
alcuni_elementi

array([2, 3, 4])

In [9]:
alcuni_elementi=mio_array[:3]
alcuni_elementi

array([1, 2, 3])

In [10]:
alcuni_elementi=mio_array[1:]
alcuni_elementi

array([2, 3, 4, 5])

In [11]:
mio_array[0]=45

In [12]:
mio_array

array([45,  2,  3,  4,  5])

In [13]:
mia_matrice=np.arange(35)

In [15]:
mia_matrice.shape=(7,5)

In [16]:
mia_matrice

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [17]:
mia_matrice[3]

array([15, 16, 17, 18, 19])

In [18]:
mia_matrice[-3]

array([20, 21, 22, 23, 24])

In [19]:
mia_matrice[-3,3]

23

In [20]:
mia_matrice[-3,3]=46

In [21]:
mia_matrice

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 46, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [22]:
mia_matrice_3d=np.arange(70)

In [23]:
mia_matrice_3d.shape=(2,7,5)

In [24]:
mia_matrice_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [25]:
mia_matrice_3d[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [26]:
mia_matrice_3d[1,4]

array([55, 56, 57, 58, 59])

In [29]:
mia_matrice_3d[1,4,2]

57

In [30]:
mia_matrice_3d[1,4,2]=134

In [31]:
mia_matrice_3d

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34]],

       [[ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56, 134,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69]]])