In [1]:
import numpy as np

In [2]:
mio_array=np.arange(1,11)
mio_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
mio_array+mio_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
mio_array-mio_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
mio_array*mio_array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
mio_array/mio_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
mio_array+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
mio_array-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
mio_array*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
mio_array/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
mio_array**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [23]:
mia_matrice=np.ones((5,5),int)
mia_matrice=mia_matrice*5
mia_matrice

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [24]:
mia_matrice+mia_matrice

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [25]:
mia_matrice-mia_matrice

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
mia_matrice*mia_matrice

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [27]:
mia_matrice/mia_matrice

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
mia_matrice**mia_matrice

array([[3125, 3125, 3125, 3125, 3125],
       [3125, 3125, 3125, 3125, 3125],
       [3125, 3125, 3125, 3125, 3125],
       [3125, 3125, 3125, 3125, 3125],
       [3125, 3125, 3125, 3125, 3125]], dtype=int32)

In [42]:
mia_matrice_sum=mia_matrice.sum()
mia_matrice_sum

3125

In [43]:
mia_matrice.dot(mia_matrice,mia_matrice)

array([[78125, 78125, 78125, 78125, 78125],
       [78125, 78125, 78125, 78125, 78125],
       [78125, 78125, 78125, 78125, 78125],
       [78125, 78125, 78125, 78125, 78125],
       [78125, 78125, 78125, 78125, 78125]])