In [1]:
import numpy as np

In [5]:
mio_array_float=np.random.rand(5)

In [6]:
mio_array_float

array([0.03131458, 0.92822765, 0.78171677, 0.9059801 , 0.87094189])

In [7]:
mia_matrice_float=np.random.rand(5,7)

In [8]:
mia_matrice_float

array([[0.45831941, 0.78377774, 0.51746679, 0.57861063, 0.70962401,
        0.66773645, 0.09512712],
       [0.7333945 , 0.43076402, 0.97156876, 0.8358296 , 0.34965121,
        0.76943945, 0.20708494],
       [0.70959961, 0.82620646, 0.53357318, 0.52088427, 0.75957216,
        0.6247006 , 0.73671678],
       [0.16612329, 0.28237997, 0.19293718, 0.0073684 , 0.1343168 ,
        0.58094063, 0.24240917],
       [0.92774394, 0.12340698, 0.78061429, 0.2021131 , 0.42089328,
        0.02866192, 0.59131874]])

In [11]:
mio_array_int=np.random.randint(5, size=10)

In [12]:
mio_array_int

array([3, 2, 0, 3, 1, 0, 3, 4, 0, 2])

In [14]:
mia_matrice_int=np.random.randint(5, size=(10,8))

In [15]:
mia_matrice_int

array([[4, 4, 2, 2, 0, 1, 2, 0],
       [4, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 2, 3, 2, 3, 4, 0],
       [0, 0, 1, 3, 0, 2, 4, 1],
       [4, 2, 2, 4, 4, 1, 4, 3],
       [0, 1, 1, 3, 2, 4, 4, 4],
       [2, 2, 3, 3, 1, 0, 3, 1],
       [1, 2, 1, 4, 3, 4, 0, 1],
       [3, 2, 1, 1, 0, 2, 4, 0],
       [1, 3, 3, 4, 1, 1, 0, 0]])